name: Process Votes

on:
  issues:
    types: [opened]

jobs:
  count-votes:
    if: contains(github.event.issue.labels.*.name, 'vote')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up jq
        run: sudo apt-get install jq

      - name: Read current votes
        id: read_votes
        run: |
          boyVotes=$(jq '.boyVotes' contents/votes.json)
          girlVotes=$(jq '.girlVotes' contents/votes.json)

          echo "BOY=$boyVotes" >> $GITHUB_ENV
          echo "GIRL=$girlVotes" >> $GITHUB_ENV

      - name: Parse issue body and update vote
        run: |
          echo "${{ github.event.issue.body }}" > body.json

          name=$(jq -r '.name' body.json)
          vote=$(jq -r '.vote' body.json)

          echo "Голос от $name: $vote"

          if [[ "$vote" == "Мальчик 💙" ]]; then
            newBoy=$((BOY+1))
            newGirl=$GIRL
          elif [[ "$vote" == "Девочка 💖" ]]; then
            newGirl=$((GIRL+1))
            newBoy=$BOY
          else
            echo "Неверный голос"
            exit 1
          fi

          echo "{\"boyVotes\": $newBoy, \"girlVotes\": $newGirl}" > contents/votes.json

      - name: Commit and push
        run: |
          git config --global user.email "bot@example.com"
          git config --global user.name "GenderBot"
          git add contents/votes.json
          git commit -m "Update votes from #${{ github.event.issue.number }}"
          git push

      - name: Close issue
        uses: peter-evans/close-issue@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: |
            Спасибо за голос, ${{ fromJson(github.event.issue.body)>name}}!
